export const sourceLinks = [
  {
    label: "Icy Veins: TBC Classic leveling guide (60-70 order)",
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    label: "Wowpedia: Zones by level (Classic)",
    url: "https://wowpedia.fandom.com/wiki/Zones_by_level_(Classic)",
  },
  {
    label: "Wowpedia: Map of Outland (zone ranges)",
    url: "https://wowpedia.fandom.com/wiki/The_Burning_Crusade_Townhall/Map_of_Outland",
  },
  {
    label: "MMORPG Tips: WoW Classic 1-60 leveling route",
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
];

export const classList = [
  "Any",
  "Warrior",
  "Paladin",
  "Hunter",
  "Rogue",
  "Priest",
  "Shaman",
  "Mage",
  "Warlock",
  "Druid",
];

export const raceList = [
  "Any",
  "Human",
  "Dwarf",
  "Draenei",
  "Gnome",
  "Night Elf",
  "Orc",
  "Tauren",
  "Troll",
  "Undead",
  "Blood Elf",
];

export const raceSpawns = {
  Any: "Varies by faction and race",
  Human: "Northshire Abbey - Elwynn Forest",
  Dwarf: "Kharanos - Dun Morogh",
  Draenei: "Ammen Vale - Azuremyst Isle",
  Gnome: "Coldridge Valley / Gnomeregan area - Dun Morogh",
  "Night Elf": "Shadowglen - Teldrassil",
  Orc: "Valley of Trials - Durotar",
  Tauren: "Camp Narache - Mulgore",
  Troll: "Sen'jin Village - Durotar",
  Undead: "Deathknell - Tirisfal Glades",
  "Blood Elf": "Sunstrider Isle - Eversong Woods",
};

export const raceFactionMap = {
  Any: "Both",
  Human: "Alliance",
  Dwarf: "Alliance",
  Draenei: "Alliance",
  Gnome: "Alliance",
  "Night Elf": "Alliance",
  Orc: "Horde",
  Tauren: "Horde",
  Troll: "Horde",
  Undead: "Horde",
  "Blood Elf": "Horde",
};

export const raceClassMap = {
  Any: classList,
  Human: ["Any", "Warrior", "Paladin", "Rogue", "Priest", "Mage", "Warlock"],
  Dwarf: ["Any", "Warrior", "Paladin", "Hunter", "Rogue", "Priest"],
  Draenei: ["Any", "Warrior", "Paladin", "Hunter", "Priest", "Shaman", "Mage"],
  Gnome: ["Any", "Warrior", "Rogue", "Mage", "Warlock"],
  "Night Elf": ["Any", "Warrior", "Hunter", "Rogue", "Priest", "Druid"],
  Orc: ["Any", "Warrior", "Hunter", "Rogue", "Shaman", "Warlock"],
  Tauren: ["Any", "Warrior", "Hunter", "Shaman", "Druid"],
  Troll: ["Any", "Warrior", "Hunter", "Rogue", "Priest", "Shaman", "Mage"],
  Undead: ["Any", "Warrior", "Rogue", "Priest", "Mage", "Warlock"],
  "Blood Elf": ["Any", "Paladin", "Hunter", "Rogue", "Priest", "Mage", "Warlock"],
};

export const quests = [
  {
    id: "alliance-starters-1",
    title: "Alliance starter hubs (1-10)",
    zone: "Elwynn / Dun Morogh / Teldrassil / Azuremyst",
    level: "1",
    faction: "Alliance",
    chain: "Classic 1-60 route",
    classPriority: ["Any"],
    prereq: [],
    url: "https://wowpedia.fandom.com/wiki/Zones_by_level_(Classic)",
  },
  {
    id: "alliance-10-16",
    title: "Westfall / Loch Modan / Darkshore sweep",
    zone: "Westfall / Loch Modan / Darkshore",
    level: "10",
    faction: "Alliance",
    chain: "Classic 1-60 route",
    classPriority: ["Hunter", "Paladin", "Warrior"],
    prereq: ["alliance-starters-1"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "alliance-16-22",
    title: "Redridge + Duskwood loop",
    zone: "Redridge Mountains / Duskwood",
    level: "16",
    faction: "Alliance",
    chain: "Classic 1-60 route",
    classPriority: ["Mage", "Warlock", "Priest"],
    prereq: ["alliance-10-16"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "horde-starters-1",
    title: "Horde starter hubs (1-10)",
    zone: "Durotar / Mulgore / Tirisfal / Eversong",
    level: "1",
    faction: "Horde",
    chain: "Classic 1-60 route",
    classPriority: ["Any"],
    prereq: [],
    url: "https://wowpedia.fandom.com/wiki/Zones_by_level_(Classic)",
  },
  {
    id: "horde-10-16",
    title: "Barrens / Silverpine / Ghostlands sweep",
    zone: "The Barrens / Silverpine / Ghostlands",
    level: "10",
    faction: "Horde",
    chain: "Classic 1-60 route",
    classPriority: ["Hunter", "Shaman", "Warrior"],
    prereq: ["horde-starters-1"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "horde-16-22",
    title: "Stonetalon + Hillsbrad loop",
    zone: "Stonetalon Mountains / Hillsbrad Foothills",
    level: "16",
    faction: "Horde",
    chain: "Classic 1-60 route",
    classPriority: ["Warlock", "Priest", "Mage"],
    prereq: ["horde-10-16"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-22-26",
    title: "Ashenvale + Stonetalon consolidation",
    zone: "Ashenvale / Stonetalon Mountains",
    level: "22",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Druid", "Rogue", "Hunter"],
    prereq: ["alliance-16-22", "horde-16-22"],
    anyPrereq: true,
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-26-30",
    title: "Thousand Needles + Hillsbrad cleanup",
    zone: "Thousand Needles / Hillsbrad Foothills",
    level: "26",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Hunter", "Warlock", "Mage"],
    prereq: ["shared-22-26"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-30-34",
    title: "Stranglethorn opening + Arathi",
    zone: "Stranglethorn Vale / Arathi Highlands",
    level: "30",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Rogue", "Hunter", "Mage"],
    prereq: ["shared-26-30"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-34-38",
    title: "Desolace + Dustwallow quest hubs",
    zone: "Desolace / Dustwallow Marsh",
    level: "34",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Mage", "Warlock", "Priest"],
    prereq: ["shared-30-34"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-38-43",
    title: "Badlands + Swamp of Sorrows",
    zone: "Badlands / Swamp of Sorrows",
    level: "38",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Warrior", "Paladin", "Shaman"],
    prereq: ["shared-34-38"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-43-47",
    title: "Tanaris + Feralas sweep",
    zone: "Tanaris / Feralas",
    level: "43",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Mage", "Warlock", "Hunter"],
    prereq: ["shared-38-43"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-47-51",
    title: "Hinterlands + Searing Gorge routes",
    zone: "The Hinterlands / Searing Gorge",
    level: "47",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Rogue", "Hunter", "Mage"],
    prereq: ["shared-43-47"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-51-55",
    title: "Un'Goro + Felwood circuits",
    zone: "Un'Goro Crater / Felwood",
    level: "51",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Druid", "Hunter", "Warlock"],
    prereq: ["shared-47-51"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-55-58",
    title: "Plaguelands + Burning Steppes",
    zone: "Western/Eastern Plaguelands / Burning Steppes",
    level: "55",
    faction: "Both",
    chain: "Classic 1-60 route",
    classPriority: ["Priest", "Paladin", "Warrior"],
    prereq: ["shared-51-55"],
    url: "https://www.mmorpgtips.com/wow-classic-leveling-guide/",
  },
  {
    id: "shared-58-60",
    title: "Blasted Lands portal prep",
    zone: "Blasted Lands",
    level: "58",
    faction: "Both",
    chain: "Classic -> Outland transition",
    classPriority: ["Any"],
    prereq: ["shared-55-58"],
    url: "https://wowpedia.fandom.com/wiki/The_Burning_Crusade_Townhall/Map_of_Outland",
  },
  {
    id: "outland-entry",
    title: "Dark Portal entry and first hub setup",
    zone: "Hellfire Peninsula",
    level: "60",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Any"],
    prereq: ["shared-58-60"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "hellfire-60-62",
    title: "Hellfire Peninsula core quest hubs",
    zone: "Hellfire Peninsula",
    level: "62",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Warrior", "Paladin", "Hunter"],
    prereq: ["outland-entry"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "zangarmarsh-62-64",
    title: "Zangarmarsh quest loops",
    zone: "Zangarmarsh",
    level: "64",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Mage", "Warlock", "Priest"],
    prereq: ["hellfire-60-62"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "terokkar-64-65",
    title: "Terokkar Forest + Shattrath chains",
    zone: "Terokkar Forest",
    level: "65",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Rogue", "Druid"],
    prereq: ["zangarmarsh-62-64"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "nagrand-65-67",
    title: "Nagrand hubs + Ring of Blood",
    zone: "Nagrand",
    level: "66",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Warrior", "Paladin", "Shaman"],
    prereq: ["terokkar-64-65"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "blades-edge-67-68",
    title: "Blade's Edge selective route",
    zone: "Blade's Edge Mountains",
    level: "67",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Warrior", "Paladin", "Shaman"],
    prereq: ["nagrand-65-67"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "netherstorm-68-69",
    title: "Netherstorm hub progression",
    zone: "Netherstorm",
    level: "68",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Mage", "Warlock", "Priest"],
    prereq: ["blades-edge-67-68"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "shadowmoon-69-70",
    title: "Shadowmoon Valley finish route",
    zone: "Shadowmoon Valley",
    level: "69",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Druid", "Hunter", "Shaman"],
    prereq: ["netherstorm-68-69"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
  {
    id: "outland-70-cleanup",
    title: "Level 70 cleanup and leftover quests",
    zone: "Netherstorm / Shadowmoon Valley",
    level: "70",
    faction: "Both",
    chain: "Outland 60-70 route",
    classPriority: ["Any"],
    prereq: ["shadowmoon-69-70"],
    url: "https://www.icy-veins.com/tbc-classic/tbc-classic-leveling-guide",
  },
];
